### ISSUE TITLE
Import location as YAML file

### ISSUE THREAD

**Issue by scls19fr** [BEMServer/bemserver-ui#128]
Hello,

In BEMServer, locations have a hierachical form.
Maybe supporting YAML import should be considered as it can be a very convenient maner to populate database with sample data.

```yaml
---
sites:
- name: Site1
  latitude: -90
  longitude: -180
  description: AAAAAA
  ifc_id: AAAAAA
  buildings:
  - name: B1
    description: AAAAAA
    ifc_id: AAAAAA
    storeys:
    - name: R0
      description: AAAAAA
      ifc_id: AAAAAA
      spaces:
      - name: ROOM1
        description: AAAAAA
        ifc_id: AAAAAA
        storey_id: 0
      - name: ROOM2
        description: AAAAAA
        ifc_id: AAAAAA
        storey_id: 0
    - name: R1
      description: AAAAAA
      ifc_id: AAAAAA
  - name: B2
    description: AAAAAA
    ifc_id: AAAAAA
```

Linting and viewing such a file can be done using online tools such as https://jsonformatter.org/yaml-viewer

Kind regards
